flash-script: fix stale hostName references after rebase
The rebase of the flash-signed-sd-image wrapper onto the post-fa3ae90
base left two `hostName` references in the new `flashScript` derivation
(both the derivation `name` and the call into `legacyFlashScript`).

Since fa3ae90 removed the `hostName` binding from `let`-scope in favour
of `cfg.name`, consumers that use the device-pkgs flashScript output
fail to evaluate with:

  error: undefined variable 'hostName'
    at device-pkgs/default.nix:160:21

Replace the remaining `${hostName}` interpolations with `${cfg.name}` to
match `legacyFlashScript`, `initrdFlashScript`, and `fuseScript`.

Signed-off-by: vadik likholetov <vadikas@gmail.com>