nvidia-oot: Apply sound include path fix for tegra-virt-alt
The sound module was failing to compile due to missing include path for
tegra_pcm_alt.h. This adds the existing patch that fixes the include path
from undefined overlay variable to the correct srctree.nvidia-oot path.

This fixes the build error:
fatal error: tegra_pcm_alt.h: No such file or directory

Signed-off-by: Julius Koskela <julius.koskela@unikie.com>